[deps]
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageInTerminal = "d8c32880-2388-543b-8c61-d9f865259254"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Solaris = "c31bc6c7-79d6-424e-a85f-5b42ee086500"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
DifferentiationInterface = "0.7"
Flux = "0.16"
ImageCore = "0.10"
ImageInTerminal = "0.5"
Lux = "^1"
MLDatasets = "0.7"
Plots = "^1"
Solaris = "0.2"
Statistics = "^1"
Zygote = "0.7"
